name: Run All

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dlang-community/setup-dlang@4c99aa991ce7d19dd3064de0a4f2f6b2f152e2d7
      
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install clang
          sudo apt-get install cmake
          sudo apt-get install ninja-build
      
      - name: "Build Advent Tool"
        run: "dub build --single ./advent.d"
      - name: "Run Advent Tool for all in 2020"
        run: "./scaffolder run day 2020 1 --show-output"
        env:
          CC: clang
          CXX: clang++
